[package]
name = "guitar-tab-generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0.71"
average = { version = "0.14.1", features = ["rayon"] }
itertools = "0.11.0"
js-sys = "0.3.64"
ordered-float = "3.7.0"
pathfinding = "4.3.0"
strum = "0.25.0"
strum_macros = "0.25.1"
thiserror = "1.0.43"
wasm-bindgen = "0.2.87"
web-sys = "0.3.64"

[profile.release]
# strip = true  # Automatically strip symbols from the binary.
# opt-level = "z"  # Optimize for size.
# lto = true
# codegen-units = 1
